### ISSUE TITLE
Incorrect password in login does not notify user

### ISSUE THREAD

**Issue by notkimroberts** [notkimroberts/collectors-trading-platform#28]

**Comment by jhhlim** [comment]
These are my debugging results:

I think the issue is in the auth/index POST for login
i was getting these issues earlier while testing:
![image](https://user-images.githubusercontent.com/31980053/98433449-06613700-207c-11eb-8c4b-4566275ab682.png)
![image](https://user-images.githubusercontent.com/31980053/98433450-095c2780-207c-11eb-8c6f-b010bd460998.png)
![image](https://user-images.githubusercontent.com/31980053/98433453-0d884500-207c-11eb-8087-df5cff624c37.png)

**Comment by tomki1** [comment]
another issue is if you are not logged in, click on login tab, then click on register tab, it will take you to the home page instead of register tab.  if you click register tab again, then it will take you to register tab

**Comment by tomki1** [comment]
i think i might have fixed it. will do PR after we fix logging in on heroku
